<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>ManagedDotNet.SignalR.Topics.Examples.Server.App</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.11" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\SignalR.Topics.csproj" />
    <ProjectReference Include="..\..\Shared\Shared.csproj" />
    <ProjectReference Include="..\Modules\Orders\Orders.csproj" />
  </ItemGroup>

</Project>
