<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>ManagedDotNet.SignalR.Topics.Examples.Server.Modules.Orders</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\src\SignalR.Topics.csproj" />
    <ProjectReference Include="..\..\..\Shared\Shared.csproj" />
  </ItemGroup>

</Project>
